name: cubegon
description: A notes sharing app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.15+19

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # WIDGETS
  flutter_svg: ^1.1.1+1
  dotted_border: ^2.0.0+2
  flutter_credit_card: ^3.0.2
  emoji_selector: ^0.0.3
  emoji_dialog_picker: ^1.0.1
  flutter_chat_ui: ^1.6.4
  grouped_buttons_ns: ^1.0.0
  my_app_library:
    path: 'packages/my_app_library'

  # REPOSITORIES
  authentication_repository:
    path: 'packages/authentication_repository'
  user_repository:
    path: 'packages/user_repository'
  api_client:
    path: 'packages/api_client'

  # ROUTER
  auto_route: ^4.2.1

  # THEME
  google_fonts: ^3.0.1
  flex_color_scheme: ^6.1.1

  #DATA and MODELS
  faker_dart: ^0.1.6
  flutter_chat_types: ^3.4.5
  uuid: ^3.0.6

  # STATE
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  freezed_annotation: ^2.1.0
  flutter_firebase_chat_core: ^1.6.3

  # NATIVE
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11

  #UTILS
  logger: ^1.1.0 # Used for logging
  dart_code_metrics: ^4.16.0 # Code Metrics
  step_progress_indicator: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.6
  hydrated_bloc: ^8.1.0
  desktop_drop: ^0.3.3
  file_picker: ^3.0.4
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  syncfusion_flutter_pdfviewer: ^20.2.50-beta
  url_launcher: ^6.1.5
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.4.9
  firebase_storage: ^10.3.9
  firebase_core_platform_interface: 4.5.1
  google_sign_in: ^5.4.2
  flutter_animate: ^1.0.0
  line_icons: ^2.0.1
  timeago: ^3.3.0
  url_strategy: ^0.2.0
  lottie: ^2.0.0
  keyboard_actions: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  auto_route_generator: ^4.2.1

  flutter_launcher_icons: '^0.10.0'

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/launcher_icon.jpg'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/launcher_icon.jpg'
    background_color: '#hexcode'
    theme_color: '#hexcode'

flutter:
  uses-material-design: true

  assets:
    - assets/404/
    - assets/web/
    - assets/mobile/
    - assets/icons/
    - assets/logo/
    - assets/navbar/
    - assets/notes/
    - assets/onboard/
    - assets/lotties/

  fonts:
    - family: Source_Sans_Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: assets/fonts/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic
